FROM node:gallium-alpine

ARG APP_PATH=/app
ARG PORT_DEV=${PORT_DEV}
# ARG PUBLIC_URL=${PUBLIC_URL}
ENV PATH=${APP_PATH}/node_modules/.bin:$PATH
ENV PUBLIC_URL=${PUBLIC_URL}
WORKDIR ${APP_PATH}

COPY package.json .

RUN apk update && apk add --update git && rm -rf /var/cache/apk/*
RUN corepack enable \
    && corepack prepare yarn@stable --activate \
    && yarn set version 3.1.1 \
    && yarn plugin import interactive-tools \
    && echo -e "nodeLinker: node-modules\n\n$(cat ${APP_PATH}/.yarnrc.yml)" > ${APP_PATH}/.yarnrc.yml \
    && yarn

COPY . .

EXPOSE ${PORT_DEV}

CMD ["yarn", "run", "start"]
