# reference: https://github.com/polkadot-js/apps/blob/master/docker/Dockerfile
FROM ubuntu:18.04 AS builder

ARG WEBSERVER_DIR="substrate-front-end-template"
WORKDIR /root/${WEBSERVER_DIR}

# override base log level (info)
ENV NPM_CONFIG_LOGLEVEL warn

# Install any needed packages
RUN apt-get update && \
  apt-get install --no-install-recommends -y curl git gnupg ca-certificates

# install nodejs and delete package info cache
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get install --no-install-recommends -y nodejs && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*
RUN npm install yarn -g

COPY package.json .
# copy all except shown in .dockerignore
COPY . .

# install dependencies
RUN yarn

# build project in build/ directory
RUN NODE_ENV=production yarn build

# ===========================================================
FROM nginx:stable-alpine

ARG WEBSERVER_DIR="substrate-front-end-template"
WORKDIR /usr/share/nginx/html

COPY ./docker/env.sh .

RUN mkdir -p /usr/share/nginx/html/${WEBSERVER_DIR};
RUN apk add --no-cache bash; chmod +x env.sh

COPY docker/nginx.conf /etc/nginx/nginx.conf
# replace default nginx index.html file
COPY --from=builder /root/${WEBSERVER_DIR}/build/index.html /usr/share/nginx/html/index.html
# all other files in WEBSERVER_DIR subfolder 
COPY --from=builder /root/${WEBSERVER_DIR}/build /usr/share/nginx/html/${WEBSERVER_DIR}

EXPOSE 80

# run nginx in debug mode (foreground)
CMD ["/bin/bash", "-c", "/usr/share/nginx/html/env.sh && nginx -g \"daemon off;\""]
